
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "@/components/layout/footer/Footer";
import { WhatsApp } from "@/components/layout/header/WhatsApp";
import { Header } from "@/components";

const alethiaNext = localFont({
  src: "../../public/assets/font/alethianext-light.otf",
  variable: "--font-alethia-next",
  display: "swap",
});

const alethiaExtraLight = localFont({
  src: "../../public/assets/font/alethianext-extralight.otf",
  variable: "--font-alethia-extralight",
  display: "swap",
});

const signatie = localFont({
  src: "../../public/assets/font/Signatie.woff2",
  variable: "--font-signatie",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alethiaNext.variable} ${signatie.variable} ${alethiaExtraLight.variable} antialiased`}
      >
        <Header />
        {children}
        <WhatsApp/>
        <Footer />
      </body>
    </html>
  );
}
